# Generated by Django 5.1.11 on 2026-07-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('degraded', 'Degraded')], default='idle', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField()),
                ('last_job_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
