# Generated by Django 5.1.11 on 2026-07-27 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worker_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deployment', models.CharField(blank=True, max_length=120)),
                ('vector_dimensions', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
