# Generated by Django 5.2.16 on 2026-08-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_householdinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditContext',
        ),
    ]
