# Generated by Django 5.2.16 on 2026-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_auditcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdiagnostic',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerdiagnostic',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
