# Generated by Django 5.2.16 on 2026-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('recipes', '0005_add_operational_diagnostics'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['plan', 'date'], name='meal_slot_plan_date_idx'),
        ),
    ]
