# Generated by Django 5.2.16 on 2026-10-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_mealslot_meal_slot_plan_date_idx'),
        ('recipes', '0015_recipeingredient_match_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookevent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cook_events', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='mealslot',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='meal_slots', to='recipes.recipe'),
        ),
    ]
