# Generated by Django 5.2.16 on 2026-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_restrict_household_internal_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealslot',
            name='course',
            field=models.CharField(blank=True, choices=[('starter', 'Vorspeise'), ('main', 'Hauptgang'), ('side', 'Beilage'), ('dessert', 'Dessert')], max_length=16),
        ),
    ]
