# Generated by Django 5.1.11 on 2026-07-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Veröffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=12),
        ),
    ]
