# Generated by Django 5.1.11 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.FileField(blank=True, upload_to="recipes/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ausstehend"),
                    ("ready", "Fertig"),
                    ("failed", "Fehlgeschlagen"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="search_embedding",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="recipe",
            name="search_embedding_model",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]