# Generated by Django 5.1.11 on 2026-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeimagejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimagejob',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeimagejob',
            name='correlation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeimagejob',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
