# Generated by Django 5.2.16 on 2026-08-03 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_householdinvitation'),
        ('recipes', '0005_add_operational_diagnostics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['household', 'status'], name='recipe_household_status_idx'),
        ),
    ]
