# Generated by Django 5.2.16 on 2026-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_recipe_household_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='recipe-thumbnails/'),
        ),
    ]
