# Generated by Django 5.2.16 on 2026-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_recipe_household_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='manual', max_length=20),
        ),
    ]
