# Generated by Django 5.2.16 on 2026-08-11 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_auditcontext'),
        ('recipes', '0006_recipe_recipe_household_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scoring_version', models.CharField(max_length=40)),
                ('inventory_snapshot_at', models.DateTimeField()),
                ('input_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='core.household')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('opened', 'Opened'), ('planned', 'Planned'), ('cooked', 'Cooked'), ('dismissed', 'Dismissed'), ('hidden', 'Hidden')], max_length=12)),
                ('reason', models.CharField(blank=True, choices=[('not_relevant', 'Not relevant'), ('too_many_ingredients', 'Too many ingredients'), ('recently_cooked', 'Recently cooked'), ('other', 'Other')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_outcomes', to='core.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_outcomes', to='recipes.recipe')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='recipes.recommendationrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['household', 'created_at'], name='recommendation_run_house_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationoutcome',
            index=models.Index(fields=['household', 'recipe', 'created_at'], name='recommendation_outcome_rec_idx'),
        ),
    ]
