# Generated by Django 5.2.17 on 2026-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_importsource_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
    ]
