# Generated by Django 5.2.16 on 2026-10-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0014_restrict_household_internal_fks'),
        ('recipes', '0015_recipeingredient_match_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recipes', to='recipes.recipesource'),
        ),
        migrations.AlterField(
            model_name='recipeimportjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='recipes.importsource'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='canonical_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recipe_lines', to='pantry.canonicalingredient'),
        ),
        migrations.AlterField(
            model_name='recipesource',
            name='import_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recipe_source', to='recipes.importsource'),
        ),
    ]
