# Generated by Django 5.2.16 on 2026-10-06 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_single_timers(apps, schema_editor):
    RecipeStep = apps.get_model("recipes", "RecipeStep")
    for step in RecipeStep.objects.filter(timer_seconds__isnull=False, timer_seconds__gt=0):
        step.timers = [{"label": "Timer", "seconds": step.timer_seconds}]
        step.save(update_fields=["timers"])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_restrict_household_internal_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='timers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_single_timers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='recipestep',
            name='timer_seconds',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='steps', to='recipes.recipeingredient'),
        ),
        migrations.CreateModel(
            name='RecipeStepEnrichmentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='queued', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_enrichment_jobs', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
