# Generated by Django 5.2.17 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0017_step_timers_and_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeimportjob",
            name="provider_response",
            field=models.TextField(blank=True),
        ),
    ]
