# Generated by Django 5.1.11 on 2026-07-25 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_categories', to='core.household')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.household')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pantry.canonicalingredient')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.ingredientcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('needs_replenishment', 'Needs replenishment'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='pantry.canonicalingredient')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('in_stock', 'In stock'), ('needs_replenishment', 'Needs replenishment'), ('unknown', 'Unknown')], max_length=24)),
                ('new_status', models.CharField(choices=[('in_stock', 'In stock'), ('needs_replenishment', 'Needs replenishment'), ('unknown', 'Unknown')], max_length=24)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Purchase'), ('cook_recipe', 'Cook recipe')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='pantry.inventoryitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='canonicalingredient',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_ingredient_name'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('household', 'ingredient'), name='one_inventory_item'),
        ),
    ]
