# Generated by Django 5.1.11 on 2026-07-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_inventoryevent_meal_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='new_status',
            field=models.CharField(choices=[('in_stock', 'Vorrätig'), ('needs_replenishment', 'Nachkaufen'), ('unknown', 'Unbekannt')], max_length=24),
        ),
        migrations.AlterField(
            model_name='inventoryevent',
            name='previous_status',
            field=models.CharField(choices=[('in_stock', 'Vorrätig'), ('needs_replenishment', 'Nachkaufen'), ('unknown', 'Unbekannt')], max_length=24),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'Vorrätig'), ('needs_replenishment', 'Nachkaufen'), ('unknown', 'Unbekannt')], default='unknown', max_length=24),
        ),
    ]
