# Generated by Django 5.2.16 on 2026-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_householdinvitation'),
        ('pantry', '0011_canonicalingredient_icon_ingredienticonjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienticonjob',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['household', 'status'], name='inventory_household_status_idx'),
        ),
    ]
