# Generated by Django 5.2.16 on 2026-10-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0013_inventory_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalingredient',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pantry.canonicalingredient'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_items', to='pantry.canonicalingredient'),
        ),
    ]
