# Generated by Django 5.1.11 on 2026-07-25 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pantry', '0002_inventoryevent_meal_slot'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='active', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.household')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='planning.mealplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('grouping_key', models.CharField(max_length=200)),
                ('quantity_components', models.JSONField(blank=True, default=list)),
                ('recipe_refs', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('calculated', 'Berechnet'), ('manual', 'Manuell')], default='calculated', max_length=12)),
                ('state', models.CharField(choices=[('open', 'Offen'), ('purchased', 'Gekauft'), ('skipped', 'Übersprungen')], default='open', max_length=12)),
                ('needs_confirmation', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_items', to='pantry.canonicalingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['state', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'calculated')), fields=('shopping_list', 'grouping_key'), name='unique_calculated_item_per_list')],
            },
        ),
    ]
