# Generated by Django 5.2.16 on 2026-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0012_ingredienticonjob_available_at_and_more'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['shopping_list', 'state'], name='shopping_item_list_state_idx'),
        ),
    ]
