# Generated by Django 5.2.16 on 2026-10-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0014_restrict_household_internal_fks'),
        ('shopping', '0003_restore_restock_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='canonical_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shopping_items', to='pantry.canonicalingredient'),
        ),
    ]
