# Generated by Django 5.2.16 on 2026-08-03 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_auditcontext'),
        ('recipes', '0006_recipe_recipe_household_status_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('scoring_version', models.CharField(max_length=40)),
                ('model_version', models.CharField(blank=True, max_length=120, null=True)),
                ('inventory_snapshot_at', models.DateTimeField()),
                ('candidate_count', models.PositiveSmallIntegerField()),
                ('query_duration_ms', models.PositiveIntegerField(default=0)),
                ('scoring_duration_ms', models.PositiveIntegerField(default=0)),
                ('generation_eligible', models.BooleanField(default=False)),
                ('generation_ineligibility_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='core.household')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('opened', 'Opened'), ('planned', 'Planned'), ('cooked', 'Cooked'), ('dismissed', 'Dismissed'), ('hidden', 'Hidden')], max_length=12)),
                ('reason', models.CharField(blank=True, choices=[('not_interested', 'Not interested'), ('too_many_missing', 'Too many missing ingredients'), ('recent_repeat', 'Recent repeat'), ('not_again', 'Not again'), ('other', 'Other')], max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='core.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
                ('recommendation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='recommendations.recommendationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['household', '-created_at'], name='rec_run_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['household', 'recommendation_run', '-created_at'], name='rec_feedback_run_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['household', 'user', 'recipe', 'active'], name='rec_feedback_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedback',
            constraint=models.UniqueConstraint(fields=('recommendation_run', 'user', 'recipe', 'outcome'), name='unique_rec_run_outcome'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('outcome', 'hidden'), models.Q(('outcome', 'dismissed'), ('reason', 'not_again')), _connector='OR')), fields=('household', 'user', 'recipe'), name='unique_active_rec_preference'),
        ),
    ]
