# Generated by Django 5.2.16 on 2026-08-03 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_providerdiagnostic_input_tokens_and_more'),
        ('recipes', '0007_alter_recipesource_type'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='queued', max_length=12)),
                ('requested_servings', models.PositiveSmallIntegerField(default=4)),
                ('prompt_version', models.CharField(default='recipe-generation-v1', max_length=40)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('provider', models.CharField(default='azure_openai', max_length=40)),
                ('deployment_version', models.CharField(max_length=120)),
                ('input_hash', models.CharField(max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retryable', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('validation_issue_codes', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reserved_input_tokens', models.PositiveIntegerField(default=0)),
                ('reserved_output_tokens', models.PositiveIntegerField(default=0)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipe_jobs', to='core.household')),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='recipes.recipe')),
                ('recommendation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='recommendations.recommendationrun')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_recipe_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', '-created_at'], name='gen_job_household_recent_idx'), models.Index(fields=['state', 'available_at'], name='gen_job_ready_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['queued', 'running'])), fields=('recommendation_run',), name='unique_active_generation_per_run')],
            },
        ),
        migrations.CreateModel(
            name='GenerationDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reserved_calls', models.PositiveIntegerField(default=0)),
                ('reserved_input_tokens', models.PositiveIntegerField(default=0)),
                ('reserved_output_tokens', models.PositiveIntegerField(default=0)),
                ('used_calls', models.PositiveIntegerField(default=0)),
                ('used_input_tokens', models.PositiveIntegerField(default=0)),
                ('used_output_tokens', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_generation_usage', to='core.household')),
            ],
            options={
                'indexes': [models.Index(fields=['household', '-date'], name='gen_usage_household_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'date'), name='unique_generation_usage_day')],
            },
        ),
    ]
